// Helper functions
function isDemoMode() {
    return localStorage.getItem("dlt_demo_mode") === "true";
}
function toggleDemoMode() {
    var isOn = isDemoMode();
    localStorage.setItem("dlt_demo_mode", isOn ? "false" : "true");
    location.reload();
}
function initDemoToggle() {
    var checkbox = document.getElementById("demo-toggle");
    if (checkbox) checkbox.checked = isDemoMode();
    var banner = document.getElementById("demo-banner");
    if (banner) banner.style.display = isDemoMode() ? "block" : "none";
}

// Dummy delay reports - 75 reports from Jan 5 to Feb 11, 2026
var DEMO_REPORTS = [
  // Week 1 - Jan 5-11 (mixed weekdays/weekend)
  { id: "demo-001", incident_date: "2026-01-05", incident_time: "07:15", station: "Earls Court", direction: "Westbound (towards Wimbledon)", category: "General Delays", delay_minutes: 5, description: "Train stuck at Earls Court, massive queue forming", reporter_name: "Sarah K", upvotes: 3, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-002", incident_date: "2026-01-05", incident_time: "08:30", station: "West Brompton", direction: "Eastbound (towards Earls Court)", category: "Overcrowding", delay_minutes: 8, description: "Absolutely rammed, can barely move", reporter_name: "James M", upvotes: 6, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-003", incident_date: "2026-01-05", incident_time: "17:45", station: "Fulham Broadway", direction: "Westbound (towards Wimbledon)", category: "General Delays", delay_minutes: 4, description: "Signal issues at Fulham Broadway", reporter_name: "Tom W", upvotes: 2, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-004", incident_date: "2026-01-06", incident_time: "07:30", station: "Parsons Green", direction: "Eastbound (towards Earls Court)", category: "General Delays", delay_minutes: 6, description: "Train doors faulty, delayed departure", reporter_name: "Lucy P", upvotes: 4, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-005", incident_date: "2026-01-06", incident_time: "08:45", station: "Wimbledon", direction: "Eastbound (towards Earls Court)", category: "Overcrowding", delay_minutes: 7, description: "So crowded, missed 2 trains already", reporter_name: "Rachel H", upvotes: 5, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-006", incident_date: "2026-01-06", incident_time: "18:00", station: "Putney Bridge", direction: "Westbound (towards Wimbledon)", category: "General Delays", delay_minutes: 5, description: "Signalling issue, delays building", reporter_name: "Mark B", upvotes: 3, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-007", incident_date: "2026-01-07", incident_time: "07:50", station: "East Putney", direction: "Eastbound (towards Earls Court)", category: "Signal Failure", delay_minutes: 12, description: "Signal failure between East Putney and Putney Bridge, this is ridiculous", reporter_name: "Anna C", upvotes: 8, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-008", incident_date: "2026-01-07", incident_time: "08:15", station: "Southfields", direction: "Both / General", category: "General Delays", delay_minutes: 4, description: "Minor delays affecting both directions", reporter_name: "Emma T", upvotes: 1, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-009", incident_date: "2026-01-07", incident_time: "17:30", station: "Wimbledon Park", direction: "Eastbound (towards Earls Court)", category: "Overcrowding", delay_minutes: 9, description: "Unbelievable crowding at peak time", reporter_name: "David S", upvotes: 7, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-010", incident_date: "2026-01-08", incident_time: "08:00", station: "Fulham Broadway", direction: "Eastbound (towards Earls Court)", category: "General Delays", delay_minutes: 5, description: "Train held at Fulham Broadway", reporter_name: "Chris L", upvotes: 2, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-011", incident_date: "2026-01-08", incident_time: "09:00", station: "West Brompton", direction: "Westbound (towards Wimbledon)", category: "General Delays", delay_minutes: 6, description: "Late running, service recovering", reporter_name: "Helen R", upvotes: 3, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-012", incident_date: "2026-01-08", incident_time: "18:15", station: "Earls Court", direction: "Westbound (towards Wimbledon)", category: "Train Cancellation", delay_minutes: 14, description: "Train cancelled, next one delayed too", reporter_name: "Mike D", upvotes: 9, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-013", incident_date: "2026-01-09", incident_time: "08:20", station: "Parsons Green", direction: "Eastbound (towards Earls Court)", category: "Overcrowding", delay_minutes: 8, description: "Peak time nightmare, everyone stuck", reporter_name: "Sophie G", upvotes: 6, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-014", incident_date: "2026-01-09", incident_time: "17:45", station: "Wimbledon", direction: "Eastbound (towards Earls Court)", category: "General Delays", delay_minutes: 7, description: "Delays building from early evening", reporter_name: "Paul F", upvotes: 4, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-015", incident_date: "2026-01-09", incident_time: "18:30", station: "Putney Bridge", direction: "Westbound (towards Wimbledon)", category: "Signal Failure", delay_minutes: 11, description: "Signal failure at Putney Bridge, what's going on?", reporter_name: "Katie N", upvotes: 7, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  // Weekend - Jan 10-11 (fewer reports)
  { id: "demo-016", incident_date: "2026-01-10", incident_time: "11:30", station: "East Putney", direction: "Both / General", category: "General Delays", delay_minutes: 3, description: "Minor delays Saturday morning", reporter_name: "Ben A", upvotes: 1, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-017", incident_date: "2026-01-11", incident_time: "15:00", station: "Fulham Broadway", direction: "Eastbound (towards Earls Court)", category: "General Delays", delay_minutes: 4, description: "Sunday service, light delays", reporter_name: "Laura J", upvotes: 0, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  // Week 2 - Jan 12-18
  { id: "demo-018", incident_date: "2026-01-12", incident_time: "07:30", station: "Wimbledon", direction: "Eastbound (towards Earls Court)", category: "General Delays", delay_minutes: 5, description: "Monday morning rush is brutal", reporter_name: "Sam E", upvotes: 3, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-019", incident_date: "2026-01-12", incident_time: "08:45", station: "Wimbledon Park", direction: "Eastbound (towards Earls Court)", category: "Overcrowding", delay_minutes: 10, description: "Absolutely packed, can't get on", reporter_name: "Olivia W", upvotes: 8, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-020", incident_date: "2026-01-12", incident_time: "17:50", station: "Earls Court", direction: "Westbound (towards Wimbledon)", category: "General Delays", delay_minutes: 6, description: "Evening rush delays mounting", reporter_name: "Dan M", upvotes: 2, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-021", incident_date: "2026-01-13", incident_time: "07:45", station: "Southfields", direction: "Eastbound (towards Earls Court)", category: "General Delays", delay_minutes: 4, description: "Delays from the start of the day", reporter_name: "Sarah K", upvotes: 2, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-022", incident_date: "2026-01-13", incident_time: "09:00", station: "Parsons Green", direction: "Both / General", category: "Signal Failure", delay_minutes: 9, description: "Signal problem at Parsons Green area", reporter_name: "James M", upvotes: 5, tfl_status_severity: 9, tfl_status_description: "Minor Delays", tfl_status_reason: "Minor signal delays affecting District line" },
  { id: "demo-023", incident_date: "2026-01-13", incident_time: "18:00", station: "West Brompton", direction: "Westbound (towards Wimbledon)", category: "Overcrowding", delay_minutes: 8, description: "Packed trains during evening peak", reporter_name: "Tom W", upvotes: 4, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-024", incident_date: "2026-01-14", incident_time: "07:50", station: "Earls Court", direction: "Eastbound (towards Wimbledon)", category: "General Delays", delay_minutes: 5, description: "Train not moving at Earls Court", reporter_name: "Lucy P", upvotes: 3, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-025", incident_date: "2026-01-14", incident_time: "08:30", station: "Fulham Broadway", direction: "Westbound (towards Wimbledon)", category: "Train Cancellation", delay_minutes: 15, description: "Train cancelled, causing major delays", reporter_name: "Rachel H", upvotes: 9, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-026", incident_date: "2026-01-14", incident_time: "17:30", station: "Putney Bridge", direction: "Eastbound (towards Earls Court)", category: "General Delays", delay_minutes: 5, description: "Service recovering after morning issues", reporter_name: "Mark B", upvotes: 1, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-027", incident_date: "2026-01-15", incident_time: "08:00", station: "East Putney", direction: "Eastbound (towards Earls Court)", category: "Overcrowding", delay_minutes: 9, description: "Ridiculous crowding, safety concerns", reporter_name: "Anna C", upvotes: 7, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-028", incident_date: "2026-01-15", incident_time: "18:15", station: "Wimbledon", direction: "Eastbound (towards Earls Court)", category: "General Delays", delay_minutes: 6, description: "Evening service running late", reporter_name: "Emma T", upvotes: 2, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-029", incident_date: "2026-01-15", incident_time: "19:00", station: "Wimbledon Park", direction: "Both / General", category: "No Announcements / Poor Comms", delay_minutes: 7, description: "No communication about the delays, very frustrating", reporter_name: "David S", upvotes: 5, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-030", incident_date: "2026-01-16", incident_time: "08:15", station: "Parsons Green", direction: "Westbound (towards Wimbledon)", category: "General Delays", delay_minutes: 4, description: "Typical morning delays", reporter_name: "Chris L", upvotes: 1, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  // Weekend - Jan 17-18
  { id: "demo-031", incident_date: "2026-01-17", incident_time: "14:30", station: "West Brompton", direction: "Both / General", category: "General Delays", delay_minutes: 3, description: "Saturday service light delays", reporter_name: "Helen R", upvotes: 0, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-032", incident_date: "2026-01-18", incident_time: "16:00", station: "Earls Court", direction: "Eastbound (towards Wimbledon)", category: "General Delays", delay_minutes: 5, description: "Sunday afternoon service", reporter_name: "Mike D", upvotes: 1, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  // Week 3 - Jan 19-25
  { id: "demo-033", incident_date: "2026-01-19", incident_time: "07:30", station: "Wimbledon", direction: "Eastbound (towards Earls Court)", category: "General Delays", delay_minutes: 6, description: "Monday morning usual suspects", reporter_name: "Sophie G", upvotes: 2, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-034", incident_date: "2026-01-19", incident_time: "08:45", station: "Southfields", direction: "Both / General", category: "Overcrowding", delay_minutes: 11, description: "Peak time crowding unbelievable", reporter_name: "Paul F", upvotes: 8, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-035", incident_date: "2026-01-19", incident_time: "18:00", station: "Fulham Broadway", direction: "Westbound (towards Wimbledon)", category: "Signal Failure", delay_minutes: 10, description: "Signal failure at Fulham Broadway, very annoying", reporter_name: "Katie N", upvotes: 6, tfl_status_severity: 9, tfl_status_description: "Minor Delays", tfl_status_reason: "Signal failure affecting District line services" },
  { id: "demo-036", incident_date: "2026-01-20", incident_time: "08:00", station: "Putney Bridge", direction: "Eastbound (towards Earls Court)", category: "General Delays", delay_minutes: 5, description: "Delays from morning rush", reporter_name: "Ben A", upvotes: 2, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-037", incident_date: "2026-01-20", incident_time: "09:15", station: "East Putney", direction: "Westbound (towards Wimbledon)", category: "Train Cancellation", delay_minutes: 13, description: "Another train cancellation, so frustrating", reporter_name: "Laura J", upvotes: 8, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-038", incident_date: "2026-01-20", incident_time: "17:45", station: "Wimbledon Park", direction: "Eastbound (towards Earls Court)", category: "General Delays", delay_minutes: 7, description: "Evening peak delays", reporter_name: "Sam E", upvotes: 3, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-039", incident_date: "2026-01-21", incident_time: "07:45", station: "Parsons Green", direction: "Both / General", category: "Overcrowding", delay_minutes: 9, description: "Massive crowding throughout morning", reporter_name: "Olivia W", upvotes: 6, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-040", incident_date: "2026-01-21", incident_time: "18:30", station: "West Brompton", direction: "Westbound (towards Wimbledon)", category: "General Delays", delay_minutes: 4, description: "Evening service running behind", reporter_name: "Dan M", upvotes: 1, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-041", incident_date: "2026-01-22", incident_time: "08:30", station: "Earls Court", direction: "Eastbound (towards Wimbledon)", category: "General Delays", delay_minutes: 6, description: "Service disrupted at main interchange", reporter_name: "Sarah K", upvotes: 4, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-042", incident_date: "2026-01-22", incident_time: "19:00", station: "Fulham Broadway", direction: "Westbound (towards Wimbledon)", category: "No Announcements / Poor Comms", delay_minutes: 5, description: "No staff communication, left hanging", reporter_name: "James M", upvotes: 3, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-043", incident_date: "2026-01-23", incident_time: "08:15", station: "Southfields", direction: "Eastbound (towards Earls Court)", category: "General Delays", delay_minutes: 5, description: "Morning routine delays", reporter_name: "Tom W", upvotes: 1, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  // Weekend - Jan 24-25 (fewer reports)
  { id: "demo-044", incident_date: "2026-01-24", incident_time: "13:00", station: "Wimbledon", direction: "Both / General", category: "General Delays", delay_minutes: 3, description: "Saturday service quiet", reporter_name: "Lucy P", upvotes: 0, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-045", incident_date: "2026-01-25", incident_time: "15:30", station: "Parsons Green", direction: "Eastbound (towards Earls Court)", category: "General Delays", delay_minutes: 4, description: "Sunday afternoon service", reporter_name: "Rachel H", upvotes: 0, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  // Week 4 - Jan 26-Feb 1 (BAD DAY: Jan 29)
  { id: "demo-046", incident_date: "2026-01-26", incident_time: "07:45", station: "Wimbledon Park", direction: "Eastbound (towards Earls Court)", category: "General Delays", delay_minutes: 6, description: "Monday morning as usual", reporter_name: "Mark B", upvotes: 2, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-047", incident_date: "2026-01-26", incident_time: "08:50", station: "East Putney", direction: "Both / General", category: "Overcrowding", delay_minutes: 10, description: "Commuters packed in like sardines", reporter_name: "Anna C", upvotes: 7, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-048", incident_date: "2026-01-27", incident_time: "08:00", station: "Putney Bridge", direction: "Westbound (towards Wimbledon)", category: "Signal Failure", delay_minutes: 8, description: "Signal issues affecting service", reporter_name: "Emma T", upvotes: 4, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-049", incident_date: "2026-01-27", incident_time: "18:00", station: "Fulham Broadway", direction: "Eastbound (towards Earls Court)", category: "General Delays", delay_minutes: 5, description: "Evening rush building", reporter_name: "David S", upvotes: 1, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-050", incident_date: "2026-01-28", incident_time: "08:30", station: "West Brompton", direction: "Both / General", category: "Overcrowding", delay_minutes: 9, description: "Peak hour nightmare", reporter_name: "Chris L", upvotes: 6, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-051", incident_date: "2026-01-28", incident_time: "17:50", station: "Wimbledon", direction: "Eastbound (towards Earls Court)", category: "General Delays", delay_minutes: 7, description: "Service running late again", reporter_name: "Helen R", upvotes: 3, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  // BAD DAY: Jan 29 with severe delays
  { id: "demo-052", incident_date: "2026-01-29", incident_time: "07:30", station: "Earls Court", direction: "Westbound (towards Wimbledon)", category: "Signal Failure", delay_minutes: 18, description: "MAJOR signal failure at Earls Court, complete chaos", reporter_name: "Mike D", upvotes: 9, tfl_status_severity: 6, tfl_status_description: "Severe Delays", tfl_status_reason: "Severe delays between Earls Court and West Brompton due to signal failure" },
  { id: "demo-053", incident_date: "2026-01-29", incident_time: "08:15", station: "West Brompton", direction: "Both / General", category: "Train Cancellation", delay_minutes: 20, description: "Cascading cancellations, service in meltdown", reporter_name: "Sophie G", upvotes: 9, tfl_status_severity: 6, tfl_status_description: "Severe Delays", tfl_status_reason: "Severe delays between Earls Court and West Brompton due to signal failure" },
  { id: "demo-054", incident_date: "2026-01-29", incident_time: "09:00", station: "Fulham Broadway", direction: "Eastbound (towards Earls Court)", category: "Reduced Service", delay_minutes: 15, description: "Severely reduced frequency, waited 25 mins", reporter_name: "Paul F", upvotes: 8, tfl_status_severity: 6, tfl_status_description: "Severe Delays", tfl_status_reason: "Severe delays between Earls Court and West Brompton due to signal failure" },
  { id: "demo-055", incident_date: "2026-01-29", incident_time: "17:30", station: "Parsons Green", direction: "Eastbound (towards Earls Court)", category: "General Delays", delay_minutes: 12, description: "Still recovering from morning signal failure", reporter_name: "Katie N", upvotes: 5, tfl_status_severity: 9, tfl_status_description: "Minor Delays", tfl_status_reason: "Continuing signal delays on District line" },
  { id: "demo-056", incident_date: "2026-01-29", incident_time: "18:45", station: "Putney Bridge", direction: "Westbound (towards Wimbledon)", category: "Overcrowding", delay_minutes: 10, description: "Massive delays in evening peak due to morning chaos", reporter_name: "Ben A", upvotes: 7, tfl_status_severity: 6, tfl_status_description: "Severe Delays", tfl_status_reason: "Continuing signal delays affecting District line" },
  { id: "demo-057", incident_date: "2026-01-30", incident_time: "08:00", station: "Southfields", direction: "Eastbound (towards Earls Court)", category: "General Delays", delay_minutes: 6, description: "Service still sluggish after yesterday", reporter_name: "Laura J", upvotes: 3, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-058", incident_date: "2026-01-30", incident_time: "18:00", station: "Wimbledon Park", direction: "Westbound (towards Wimbledon)", category: "General Delays", delay_minutes: 5, description: "Evening service back to normal", reporter_name: "Sam E", upvotes: 1, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-059", incident_date: "2026-01-31", incident_time: "08:30", station: "East Putney", direction: "Both / General", category: "Overcrowding", delay_minutes: 8, description: "Busy Friday morning", reporter_name: "Olivia W", upvotes: 4, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-060", incident_date: "2026-02-01", incident_time: "14:00", station: "Wimbledon", direction: "Eastbound (towards Earls Court)", category: "General Delays", delay_minutes: 3, description: "Weekend service minimal delays", reporter_name: "Dan M", upvotes: 0, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  // Week 5 - Feb 2-8
  { id: "demo-061", incident_date: "2026-02-02", incident_time: "07:50", station: "Parsons Green", direction: "Eastbound (towards Earls Court)", category: "General Delays", delay_minutes: 5, description: "Monday morning delays", reporter_name: "Sarah K", upvotes: 2, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-062", incident_date: "2026-02-02", incident_time: "09:00", station: "Fulham Broadway", direction: "Westbound (towards Wimbledon)", category: "General Delays", delay_minutes: 6, description: "Late running from the start", reporter_name: "James M", upvotes: 2, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-063", incident_date: "2026-02-02", incident_time: "17:45", station: "West Brompton", direction: "Both / General", category: "Overcrowding", delay_minutes: 10, description: "Evening peak packed beyond capacity", reporter_name: "Tom W", upvotes: 7, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-064", incident_date: "2026-02-03", incident_time: "08:15", station: "Wimbledon", direction: "Eastbound (towards Earls Court)", category: "Signal Failure", delay_minutes: 9, description: "Signal problem disrupting service", reporter_name: "Lucy P", upvotes: 5, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-065", incident_date: "2026-02-03", incident_time: "18:30", station: "Earls Court", direction: "Westbound (towards Wimbledon)", category: "General Delays", delay_minutes: 4, description: "Evening service slow", reporter_name: "Rachel H", upvotes: 1, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-066", incident_date: "2026-02-04", incident_time: "07:45", station: "Putney Bridge", direction: "Eastbound (towards Earls Court)", category: "Train Cancellation", delay_minutes: 13, description: "Train cancelled at peak time, disaster", reporter_name: "Mark B", upvotes: 8, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-067", incident_date: "2026-02-04", incident_time: "17:50", station: "Southfields", direction: "Westbound (towards Wimbledon)", category: "General Delays", delay_minutes: 6, description: "Afternoon delays affecting commuters", reporter_name: "Anna C", upvotes: 3, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-068", incident_date: "2026-02-05", incident_time: "08:00", station: "East Putney", direction: "Both / General", category: "Overcrowding", delay_minutes: 9, description: "Can't fit another person on train", reporter_name: "Emma T", upvotes: 6, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-069", incident_date: "2026-02-05", incident_time: "18:00", station: "Wimbledon Park", direction: "Eastbound (towards Earls Court)", category: "General Delays", delay_minutes: 5, description: "Service recovering after morning peak", reporter_name: "David S", upvotes: 1, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-070", incident_date: "2026-02-05", incident_time: "19:15", station: "Parsons Green", direction: "Westbound (towards Wimbledon)", category: "No Announcements / Poor Comms", delay_minutes: 5, description: "No updates on the cause of delays", reporter_name: "Chris L", upvotes: 2, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-071", incident_date: "2026-02-06", incident_time: "08:45", station: "Fulham Broadway", direction: "Eastbound (towards Earls Court)", category: "General Delays", delay_minutes: 5, description: "Friday morning rush delays", reporter_name: "Helen R", upvotes: 1, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  // Weekend - Feb 7-8 (fewer reports)
  { id: "demo-072", incident_date: "2026-02-07", incident_time: "15:00", station: "West Brompton", direction: "Both / General", category: "General Delays", delay_minutes: 4, description: "Saturday afternoon light service", reporter_name: "Mike D", upvotes: 0, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  // Week 6 - Feb 9-11
  { id: "demo-073", incident_date: "2026-02-09", incident_time: "07:45", station: "Wimbledon", direction: "Eastbound (towards Earls Court)", category: "General Delays", delay_minutes: 6, description: "Monday morning back to the grind", reporter_name: "Sophie G", upvotes: 3, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-074", incident_date: "2026-02-09", incident_time: "08:50", station: "Earls Court", direction: "Westbound (towards Wimbledon)", category: "Safety Concern", delay_minutes: 8, description: "Platform crowding creating safety issues", reporter_name: "Paul F", upvotes: 5, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null },
  { id: "demo-075", incident_date: "2026-02-11", incident_time: "17:50", station: "Putney Bridge", direction: "Westbound (towards Wimbledon)", category: "General Delays", delay_minutes: 5, description: "Typical Tuesday evening delays", reporter_name: "Katie N", upvotes: 2, tfl_status_severity: 10, tfl_status_description: "Good Service", tfl_status_reason: null }
];

// Dummy TfL Daily aggregated data - 14 days from Jan 29 to Feb 11, 2026
var DEMO_TFL_DAILY = [
  { date: "2026-01-29", total: 84, disrupted: 22, wimbledon_disrupted: 3 },
  { date: "2026-01-30", total: 80, disrupted: 0, wimbledon_disrupted: 0 },
  { date: "2026-01-31", total: 72, disrupted: 0, wimbledon_disrupted: 0 },
  { date: "2026-02-01", total: 48, disrupted: 0, wimbledon_disrupted: 0 },
  { date: "2026-02-02", total: 84, disrupted: 0, wimbledon_disrupted: 0 },
  { date: "2026-02-03", total: 80, disrupted: 2, wimbledon_disrupted: 0 },
  { date: "2026-02-04", total: 80, disrupted: 0, wimbledon_disrupted: 0 },
  { date: "2026-02-05", total: 76, disrupted: 0, wimbledon_disrupted: 0 },
  { date: "2026-02-06", total: 80, disrupted: 0, wimbledon_disrupted: 0 },
  { date: "2026-02-07", total: 52, disrupted: 0, wimbledon_disrupted: 0 },
  { date: "2026-02-08", total: 56, disrupted: 0, wimbledon_disrupted: 0 },
  { date: "2026-02-09", total: 88, disrupted: 4, wimbledon_disrupted: 2 },
  { date: "2026-02-10", total: 80, disrupted: 0, wimbledon_disrupted: 0 },
  { date: "2026-02-11", total: 84, disrupted: 0, wimbledon_disrupted: 0 }
];
